const PREFS=[["北海道","016000"],["青森県","020000"],["岩手県","030000"],["宮城県","040000"],["秋田県","050000"],["山形県","060000"],["福島県","070000"],["茨城県","080000"],["栃木県","090000"],["群馬県","100000"],["埼玉県","110000"],["千葉県","120000"],["東京都","130000"],["神奈川県","140000"],["新潟県","150000"],["富山県","160000"],["石川県","170000"],["福井県","180000"],["山梨県","190000"],["長野県","200000"],["岐阜県","210000"],["静岡県","220000"],["愛知県","230000"],["三重県","240000"],["滋賀県","250000"],["京都府","260000"],["大阪府","270000"],["兵庫県","280000"],["奈良県","290000"],["和歌山県","300000"],["鳥取県","310000"],["島根県","320000"],["岡山県","330000"],["広島県","340000"],["山口県","350000"],["徳島県","360000"],["香川県","370000"],["愛媛県","380000"],["高知県","390000"],["福岡県","400000"],["佐賀県","410000"],["長崎県","420000"],["熊本県","430000"],["大分県","440000"],["宮崎県","450000"],["鹿児島県","460100"],["沖縄県","471000"]];
const $=id=>document.getElementById(id);
function icon(code,text=""){const c=String(code||"");if(c.startsWith("1"))return"☀️";if(c.startsWith("2"))return"☁️";if(c.startsWith("3"))return"🌧️";if(c.startsWith("4"))return"❄️";if(text.includes("雷"))return"⛈️";return"🌤️"}
function hm(d){return d.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}
function dayName(iso,i){if(i===0)return"今日";return["日","月","火","水","木","金","土"][new Date(iso).getDay()]}
function calcWbgt(max,weather){let v=Number(max);if(!Number.isFinite(v))return NaN;v=v-3+(weather.includes("晴")?2:0)-(weather.includes("雨")?1:0);return Math.round(Math.max(18,Math.min(35,v))*10)/10}
function setWbgt(v){const card=$("wbgtCard");card.className="glass-panel wbgt-card";document.querySelectorAll(".risk-scale span").forEach(s=>s.classList.remove("active"));let lv="ほぼ安全",cls="wbgt-safe",msg="通常時も水分補給を意識しましょう。",risk="";if(v>=31){lv="危険";cls="wbgt-danger";msg="屋外作業・運動は原則中止。涼しい場所で休憩してください。";risk="danger"}else if(v>=28){lv="厳重警戒";cls="wbgt-severe";msg="長時間の屋外作業は避け、休憩を多めに取ってください。";risk="severe"}else if(v>=25){lv="警戒";cls="wbgt-warning";msg="こまめな水分・塩分補給をしてください。";risk="warning"}else if(v>=21){lv="注意";cls="wbgt-caution";msg="暑さに慣れていない人は無理をしないでください。";risk="caution"}card.classList.add(cls);document.querySelector(`.risk-scale span[data-risk="${risk}"]`)?.classList.add("active");$("wbgtValue").textContent=Number.isFinite(v)?v.toFixed(1):"--";$("wbgtLevel").textContent=lv;$("wbgtMessage").textContent=msg}
function fillSelects(){[$("prefSelect"),$("prefSelectSettings")].forEach(s=>{s.innerHTML="";PREFS.forEach(p=>{const o=document.createElement("option");o.value=p[1];o.textContent=p[0];s.appendChild(o)})});const code=localStorage.getItem("prefCode")||"290000";$("prefSelect").value=code;$("prefSelectSettings").value=code}
function restoreSettings(){$("topMessage").textContent=localStorage.getItem("topText")||"本日の気象情報";$("tickerText").textContent=localStorage.getItem("tickerText")||"熱中症対策：こまめな水分補給と休憩を心がけましょう。";$("topTextInput").value=$("topMessage").textContent;$("tickerInput").value=$("tickerText").textContent;setMode(localStorage.getItem("forecastMode")||"hourly",false)}
async function update(){const code=$("prefSelect").value;localStorage.setItem("prefCode",code);$("prefSelectSettings").value=code;const pref=PREFS.find(p=>p[1]===code)?.[0]||"選択地域";$("areaName").textContent=pref;try{const res=await fetch(`https://www.jma.go.jp/bosai/forecast/data/forecast/${code}.json`,{cache:"no-store"});const data=await res.json();const t=data[0].timeSeries,w=t[0].areas[0],p=t[1].areas[0],temp=t[2].areas[0];const weather=(w.weathers?.[0]||"---").replaceAll("　"," ");const max=temp.temps?.[1]??"--",min=temp.temps?.[0]??"--";$("weatherText").textContent=weather;$("tempNow").textContent=max;$("highTemp").textContent=max;$("lowTemp").textContent=min;$("pop").textContent=`${p.pops?.[0]??"--"}%`;$("updatedAt").textContent=hm(new Date());$("summaryText").textContent=`${weather}が予想されています。降水確率は${p.pops?.[0]??"--"}%です。`;setWbgt(calcWbgt(max,weather));renderHourly(t,weather,max);renderWeekly(data[1].timeSeries)}catch(e){console.error(e);$("weatherText").textContent="取得失敗";$("summaryText").textContent="気象庁APIの取得に失敗しました。時間をおいて再読み込みしてください。"}}
function renderHourly(t,weather,max){const panel=$("hourlyPanel");panel.innerHTML="";const base=new Date();const pops=t[1].areas[0]?.pops||[];for(let i=0;i<12;i++){const d=new Date(base.getTime()+i*60*60*1000);const temp=Math.max(0,Math.round((Number(max)||25)-Math.max(0,i-2)*0.45));const code=i%5===0?"200":(weather.includes("雨")?"300":"100");const el=document.createElement("div");el.className="hour-card";el.innerHTML=`<div class="hour-time">${i===0?"NOW":String(d.getHours()).padStart(2,"0")+"時"}</div><div class="hour-icon">${icon(code,weather)}</div><div class="hour-temp">${temp}</div><div class="hour-pop">${pops[Math.min(i,pops.length-1)]??"--"}%</div>`;panel.appendChild(el)}}
function renderWeekly(weekly){const panel=$("weeklyPanel");panel.innerHTML="";const times=weekly[0].timeDefines||[],codes=weekly[0].areas[0].weatherCodes||[],pops=weekly[1].areas[0].pops||[],tb=weekly[1].areas[1]||weekly[1].areas[0],mins=tb.tempsMin||[],maxs=tb.tempsMax||[];for(let i=0;i<Math.min(7,times.length);i++){const el=document.createElement("div");el.className="day-row";el.innerHTML=`<div class="day-name">${dayName(times[i],i)}</div><div class="day-icon">${icon(codes[i])}<small>${pops[i]??"--"}%</small></div><div class="temp-bar"><span></span></div><div><span class="day-min">${mins[i]??"--"}</span><span class="day-max"> ${maxs[i]??"--"}</span></div>`;panel.appendChild(el)}}
function setMode(mode,save=true){const hourly=mode==="hourly";$("hourlyPanel").classList.toggle("hidden",!hourly);$("weeklyPanel").classList.toggle("hidden",hourly);$("modeLabel").textContent=hourly?"時間別":"週間";$("forecastSmallTitle").textContent=hourly?"HOURLY FORECAST":"WEEKLY FORECAST";$("forecastTitle").textContent=hourly?"現在から12時間":"週間予報";$("hourlyModeBtn").classList.toggle("active",hourly);$("weeklyModeBtn").classList.toggle("active",!hourly);if(save)localStorage.setItem("forecastMode",mode)}
function openSettings(){document.getElementById("modalBackdrop").classList.remove("hidden");$("settingsPanel").classList.remove("hidden")}
function closeSettings(){document.getElementById("modalBackdrop").classList.add("hidden");$("settingsPanel").classList.add("hidden")}
function init(){fillSelects();restoreSettings();$("prefSelect").addEventListener("change",update);$("settingsBtn").onclick=openSettings;$("closeSettings").onclick=closeSettings;$("modalBackdrop").onclick=closeSettings;$("hourlyModeBtn").onclick=()=>setMode("hourly");$("weeklyModeBtn").onclick=()=>setMode("weekly");$("saveSettings").onclick=()=>{localStorage.setItem("topText",$("topTextInput").value);localStorage.setItem("tickerText",$("tickerInput").value);localStorage.setItem("prefCode",$("prefSelectSettings").value);$("topMessage").textContent=$("topTextInput").value;$("tickerText").textContent=$("tickerInput").value;$("prefSelect").value=$("prefSelectSettings").value;closeSettings();update()};update();setInterval(update,10*60*1000)}
document.addEventListener("DOMContentLoaded",init);